app/routes.php
<?php

Route::get('c_test', function(){
    //$user = User::find(2);
//    dd($user);
    $user = new User();

    $user->username = 'asdasd';
    $user->email = 'angorusadf@gmail.com';
    $user->password = '12312312';
    $user->password_confirmation = '12312312';

    $user->save();

});

Route::group(array('before' => 'auth'), function(){
    Route::controller('translations', 'Barryvdh\TranslationManager\Controller');
});

Route::group(['namespace' => 'payment'], function(){
    include(app_path().'/routes/payment.php');
});

Route::group(array('prefix' => LaravelLocalization::setLocale()), function(){

  include(app_path().'/routes/login.php');
  include(app_path().'/routes/non-member.php');

  Route::group(['before' => 'auth'], function(){
    include(app_path().'/routes/admin.php');
    include(app_path().'/routes/modules.php');
    include(app_path().'/routes/company.php');
    include(app_path().'/routes/user.php');
    include(app_path().'/routes/default.php');
    include(app_path() . '/routes/home.php');

    Route::group(['prefix' => 'app/render'], function(){
      Route::get('{any}',                           'RenderAppController@index');
      Route::post('{any}',                           'RenderAppController@save');
    });

    Route::group(['namespace' => 'modules', 'prefix' => ''], function(){
      include(app_path().'/routes/modules.php');
    });

  });

});

Route::get('test/menu','TestController@menu');





Validator::extend('alphaspacepunc', function ($attribute, $value, $parameters) {
    return preg_match('/^[a-zA-Z0-9,\.\s]*$/', $value);
});

Validator::replacer('alphaspacepunc', function ($message, $attribute, $parameters) {
    // this might not be how its done ... i will have to check the source
    return "String must contain only alphanumeric, spaces, commas or periods.";
});

Validator::extend('current_password', function ($attribute, $value, $parameters) {

    if(Hash::check($value, Auth::user()->password)) {
        return true;
    }

    Helpers\LogbookH::createLog('logbook.profile', 0, 'logbook_messages.wrong_password', 0, 1 );


});

Validator::replacer('current_password', function ($message, $attribute, $parameters) {
    // this might not be how its done ... i will have to check the source
    return Lang::get('validation.current_password_wrong');
});



Route::get('/pdf', function(){

});

Route::get('test/pdf/{bill_id}', 'TestController@pdf');

app/models/Role.php
<?php

use Zizaco\Entrust\EntrustRole;

class Role extends EntrustRole
{
    protected $fillable = ['id', 'name', 'description'];

    public function getUsers()
    {
        return $this->hasMany('User');
    }

    public function getRoles()
    {
        return $this->belongsToMany('Permission');
    }
}

app/models/User.php
<?php

use Zizaco\Confide\ConfideUser;
use Zizaco\Entrust\HasRole;

class User extends ConfideUser {

    use HasRole;

	protected $fillable = ['id', 'token', 'first_name', 'surname', 'username', 'password', 'email', 'created_at', 'updated_at', 'confirmed', 'confirmation_code', 'phonenumber', 'role'];

    public static $rules = array(
        'email' => 'required|email',
        'password' => 'required|between:4,11|confirmed',
//        'password_confirmation' => 'required'
    );

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'users';

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = array('password');

	/**
	 * Get the unique identifier for the user.
	 *
	 * @return mixed
	 */
	public function getAuthIdentifier()
	{
		return $this->getKey();
	}

	/**
	 * Get the password for the user.
	 *
	 * @return string
	 */
	public function getAuthPassword()
	{
		return $this->password;
	}

	/**
	 * Get the e-mail address where password reminders are sent.
	 *
	 * @return string
	 */
	public function getReminderEmail()
	{
		return $this->email;
	}

	public function getCompanies()
	{
		return $this->belongsToMany('Company');
	}

	public function getUser(){
		return $this->hasMany('Company');
	}

    public function getRole(){
        return $this->belongsTo('Role');
    }

	public function logs($limit = null){
		$query = $this->hasMany('Logbook')->where('system_log', '=', 0)->get();

		if($limit != null){
			$query = $this->hasMany('Logbook')->where('system_log', '=', 0)->limit($limit)->get();
		}
		return $query;
	}
}

app/views/admin/template/master.blade.php
<!DOCTYPE html>
<html lang="nl">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta current_language="{{ strtolower(LaravelLocalization::getCurrentLocaleName()) }}"/>

    <title>SB Admin 2 - Bootstrap Admin Theme</title>

    <!-- Bootstrap Core CSS -->
    {{ HTML::style('template/admin/css/bootstrap.css'); }}

    <!-- Add custom CSS here -->
    {{ HTML::style('template/admin/css/default-css.css'); }}

    <!-- MetisMenu CSS -->
    {{ HTML::style('template/admin/css/plugins/metisMenu/metisMenu.min.css'); }}

    <!-- Timeline CSS -->
    {{ HTML::style('template/admin/css/plugins/timeline.css'); }}

    <!-- Custom CSS -->
    {{ HTML::style('template/admin/css/sb-admin-2.css'); }}

    <!-- Morris Charts CSS -->
    {{ HTML::style('template/admin/css/plugins/morris.css'); }}

    <!-- Custom Fonts -->
    {{ HTML::style('template/admin/css/font-awesome.min.css'); }}

    {{ HTML::script('//code.jquery.com/jquery-1.10.2.js') }}
    {{ HTML::script('//code.jquery.com/ui/1.10.4/jquery-ui.js') }}

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

<div id="wrapper">

    <!-- Navigation -->
    @include('admin.template.navbar-header')
    <!-- /.navbar-header -->


    <!-- /.navbar-static-side -->


    <div id="page-wrapper">
        @yield('admin_content', 'Default content')
    </div>
    <!-- /#page-wrapper -->

</div>
<!-- /#wrapper -->

<!-- jQuery -->
{{HTML::script('template/admin/js/jquery.js')}}

<!-- Bootstrap Core JavaScript -->
{{HTML::script('template/admin/js/bootstrap.min.js')}}


<!-- Metis Menu Plugin JavaScript -->
{{HTML::script('template/admin/js/plugins/metisMenu/metisMenu.min.js')}}


<!-- Morris Charts JavaScript -->
{{HTML::script('template/admin/js/plugins/morris/raphael.min.js')}}



<!-- Custom Theme JavaScript -->
{{HTML::script('template/admin/js/sb-admin-2.js')}}



</body>

</html>

app/views/admin/template/navbar-header.blade.php
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
<div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="{{url('/')}}">SimpleApp</a>
</div>

<!-- TOP RIGHT -->
<ul class="nav navbar-top-links navbar-right">
<li class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
        <i class="fa fa-envelope fa-fw"></i>  <i class="fa fa-caret-down"></i>
    </a>
    <ul class="dropdown-menu dropdown-messages">
        <li>
            <a href="#">
                <div>
                    <strong>{{Auth::user()->username}}</strong>
                                    <span class="pull-right text-muted">
                                        <em>Yesterday</em>
                                    </span>
                </div>
                <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
            </a>
        </li>
        <li class="divider"></li>
        <li>
            <a href="#">
                <div>
                    <strong>John Smith</strong>
                                    <span class="pull-right text-muted">
                                        <em>Yesterday</em>
                                    </span>
                </div>
                <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
            </a>
        </li>
        <li class="divider"></li>
        <li>
            <a href="#">
                <div>
                    <strong>John Smith</strong>
                                    <span class="pull-right text-muted">
                                        <em>Yesterday</em>
                                    </span>
                </div>
                <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
            </a>
        </li>
        <li class="divider"></li>
        <li>
            <a class="text-center" href="#">
                <strong>Read All Messages</strong>
                <i class="fa fa-angle-right"></i>
            </a>
        </li>
    </ul>
    <!-- /.dropdown-messages -->
</li>
<!-- /.dropdown -->
<li class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
        <i class="fa fa-tasks fa-fw"></i>  <i class="fa fa-caret-down"></i>
    </a>
    <ul class="dropdown-menu dropdown-tasks">
        <li>
            <a href="#">
                <div>
                    <p>
                        <strong>Task 1</strong>
                        <span class="pull-right text-muted">40% Complete</span>
                    </p>
                    <div class="progress progress-striped active">
                        <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
                            <span class="sr-only">40% Complete (success)</span>
                        </div>
                    </div>
                </div>
            </a>
        </li>
        <li class="divider"></li>
        <li>
            <a href="#">
                <div>
                    <p>
                        <strong>Task 2</strong>
                        <span class="pull-right text-muted">20% Complete</span>
                    </p>
                    <div class="progress progress-striped active">
                        <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 20%">
                            <span class="sr-only">20% Complete</span>
                        </div>
                    </div>
                </div>
            </a>
        </li>
        <li class="divider"></li>
        <li>
            <a href="#">
                <div>
                    <p>
                        <strong>Task 3</strong>
                        <span class="pull-right text-muted">60% Complete</span>
                    </p>
                    <div class="progress progress-striped active">
                        <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%">
                            <span class="sr-only">60% Complete (warning)</span>
                        </div>
                    </div>
                </div>
            </a>
        </li>
        <li class="divider"></li>
        <li>
            <a href="#">
                <div>
                    <p>
                        <strong>Task 4</strong>
                        <span class="pull-right text-muted">80% Complete</span>
                    </p>
                    <div class="progress progress-striped active">
                        <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 80%">
                            <span class="sr-only">80% Complete (danger)</span>
                        </div>
                    </div>
                </div>
            </a>
        </li>
        <li class="divider"></li>
        <li>
            <a class="text-center" href="#">
                <strong>See All Tasks</strong>
                <i class="fa fa-angle-right"></i>
            </a>
        </li>
    </ul>
    <!-- /.dropdown-tasks -->
</li>
<!-- /.dropdown -->
<li class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
        <i class="fa fa-bell fa-fw"></i>  <i class="fa fa-caret-down"></i>
    </a>
    <ul class="dropdown-menu dropdown-alerts">
        <li>
            <a href="#">
                <div>
                    <i class="fa fa-comment fa-fw"></i> New Comment
                    <span class="pull-right text-muted small">4 minutes ago</span>
                </div>
            </a>
        </li>
        <li class="divider"></li>
        <li>
            <a href="#">
                <div>
                    <i class="fa fa-twitter fa-fw"></i> 3 New Followers
                    <span class="pull-right text-muted small">12 minutes ago</span>
                </div>
            </a>
        </li>
        <li class="divider"></li>
        <li>
            <a href="#">
                <div>
                    <i class="fa fa-envelope fa-fw"></i> Message Sent
                    <span class="pull-right text-muted small">4 minutes ago</span>
                </div>
            </a>
        </li>
        <li class="divider"></li>
        <li>
            <a href="#">
                <div>
                    <i class="fa fa-tasks fa-fw"></i> New Task
                    <span class="pull-right text-muted small">4 minutes ago</span>
                </div>
            </a>
        </li>
        <li class="divider"></li>
        <li>
            <a href="#">
                <div>
                    <i class="fa fa-upload fa-fw"></i> Server Rebooted
                    <span class="pull-right text-muted small">4 minutes ago</span>
                </div>
            </a>
        </li>
        <li class="divider"></li>
        <li>
            <a class="text-center" href="#">
                <strong>See All Alerts</strong>
                <i class="fa fa-angle-right"></i>
            </a>
        </li>
    </ul>
    <!-- /.dropdown-alerts -->
</li>
<!-- /.dropdown -->
<li class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
        <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
    </a>
    <ul class="dropdown-menu dropdown-user">
        <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
        </li>
        <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
        </li>
        <li class="divider"></li>
        <li><a href="login.html"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
        </li>
    </ul>
    <!-- /.dropdown-user -->
</li>
<!-- /.dropdown -->
</ul>

@include('admin.template.navbar-left')



</nav>

app/views/admin/template/navbar-left.blade.php
<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">

        <ul class="nav" id="side-menu">



            <li>
                <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> {{Lang::get('menu.companies')}}<span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="{{url('admin/companies')}}">{{Lang::get('menu.show_companies')}}</a>
                    </li>
                    <li>
                        <a href="{{url('admin/companies/create')}}">{{Lang::get('menu.create_company')}}</a>
                    </li>
                </ul>
                <!-- /.nav-second-level -->
            </li>
            <li>
                <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> {{Lang::get('menu.users')}}<span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="{{url('admin/users')}}">{{Lang::get('menu.show_users')}}</a>
                    </li>
                    <li>
                        <a href="{{url('admin/users/create')}}">{{Lang::get('menu.create_user')}}</a>
                    </li>
                </ul>
                <!-- /.nav-second-level -->
            </li>
            <li>
                <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> {{Lang::get('menu.news')}}<span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="{{url('admin/news')}}">{{Lang::get('menu.show_news')}}</a>
                    </li>
                    <li>
                        <a href="{{url('admin/news/create')}}">{{Lang::get('menu.create_news')}}</a>
                    </li>
                </ul>
                <!-- /.nav-second-level -->
            </li>
            <li>
                <a href="{{url('admin/logbook')}}"><i class="fa fa-table fa-fw"></i> {{Lang::get('menu.logbook')}}</a>
            </li>
            <li>
                <a href="{{url('admin/news')}}"><i class="fa fa-table fa-fw"></i> {{Lang::get('menu.news')}}</a>
            </li>
            <li>
                <a href="{{url('admin/invoices')}}"><i class="fa fa-edit fa-fw"></i> {{Lang::get('menu.invoices')}}</a>
            </li>
            <li>
                <a href="#"><i class="fa fa-wrench fa-fw"></i> {{Lang::get('menu.settings')}}<span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="{{url('admin/roles')}}">{{Lang::get('menu.roles')}}</a>
                    </li>
                    <li>
                        <a href="{{url('admin/permissions')}}">{{Lang::get('menu.permissions')}}</a>
                    </li>


                </ul>
                <!-- /.nav-second-level -->
            </li>
            <li>
                <a href="#"><i class="fa fa-sitemap fa-fw"></i> {{Lang::get('menu.payment_plans')}}<span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="#">{{Lang::get('menu.show_plans')}}</a>
                    </li>
                    <li>
                        <a href="#">{{Lang::get('menu.create_plan')}}</a>
                    </li>
                </ul>
                <!-- /.nav-second-level -->
            </li>
            <li>
                <a href="#"><i class="fa fa-files-o fa-fw"></i> Sample Pages<span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="blank.html">Blank Page</a>
                    </li>
                    <li>
                        <a href="login.html">Login Page</a>
                    </li>
                </ul>
                <!-- /.nav-second-level -->
            </li>
        </ul>
    </div>
    <!-- /.sidebar-collapse -->
</div>